[phases.setup]
nixPkgs = ['tesseract', 'poppler_utils', 'python311']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements_railway.txt']

[start]
cmd = 'gunicorn web_app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120'
