[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "tesseract", "poppler_utils"]

[phases.install]
cmds = ["/root/.nix-profile/bin/pip install -r requirements.txt --no-cache-dir"]

[phases.build]
cmds = ["echo 'Build complete - using full pip path'"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --access-logfile - --error-logfile -"