[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PYTHONUNBUFFERED = "1"
